server:
  port: 8764



spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  http:
#    multipart:
#      max-file-size: 2000Mb
  profiles:
      active: dev

management:
  endpoint:
    shutdown:
      enabled: false
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8764

# management 端点
#  auditevents	公开当前应用程序的审计事件信息。
#  beans	显示应用程序中所有Spring bean的完整列表。
#  configprops	显示应用中配置的属性信息报告。
#  env	显示应用中所有可用的环境属性报告，包括环境变量、JVM属性、应用的配置属性、命令行的参数。
#  health	显示应用健康信息。
#  httptrace	显示HTTP跟踪信息（默认情况下为最后100个HTTP请求 - 响应交换）。
#  info	显示应用的自定义信息，默认是空。
#  metrics	显示当前应用程序的“指标”信息，如内存信息、线程信息。
#  mappings	显示所有url映射。
#  scheduledtasks	显示应用程序中的计划任务。
#  shutdown	让应用程序正常关机。
#  threaddump	程序运行中的线程信息。

basecfg:
  charset: utf-8
  connectTimeout: 5000
  readTimeout: 5000

name: 张三


######

workgroup:
  name: 监控
  boss:
    userId: 1001
    userName: 张三疯
    loginName: zhangsanfeng
    sex: 1
  roles:
    - admin
    - listen

workgroup2:
  name: 测试
  boss:
    userId: 1002
    userName: 大眼睛
    loginName: dayanjing
    sex: 0
  roles:
    - admin
    - listen



# list map
test-list-map:
  list:
    - userId: 2001
      userName: 马三立
      loginName: msl
      sex: 1
    - userId: 2002
      userName: 张铁生
      loginName: zts
      sex: 1
    - userId: 2003
      userName: 王菲
      loginName: wangfei
      sex: 0
  map:
    2001:
      userId: 2001
      userName: 马三立
      loginName: msl
      sex: 1
    2002:
      userId: 2004
      userName: 罗伯尼克



---
spring:
  profiles: default

workgroup3:
  name: 产品
  boss:
    userId: 1003
    userName: 馒头人
    loginName: mantouren
    sex: 1
  roles:
    - admin
    - product







